# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestXd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_xd(self):
    # Test name: xd
    # Step # | name | target | value
    # 1 | open | /menu/personales-y-para-compartir/cajun-full | 
    self.driver.get("https://ppys-dev.jnq.io/menu/personales-y-para-compartir/cajun-full")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.btn:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 4 | click | css=.line-orange | 
    self.driver.find_element(By.CSS_SELECTOR, ".line-orange").click()
    # 5 | click | css=.btn-pay | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-pay").click()
    # 6 | click | css=.icon-pay > input | 
    self.driver.find_element(By.CSS_SELECTOR, ".icon-pay > input").click()
    # 7 | type | css=.icon-pay > input | 25
    self.driver.find_element(By.CSS_SELECTOR, ".icon-pay > input").send_keys("25")
    # 8 | click | id=terminosCondiciones | 
    self.driver.find_element(By.ID, "terminosCondiciones").click()
    # 9 | click | css=.large | 
    self.driver.find_element(By.CSS_SELECTOR, ".large").click()
  
