# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | /menu/personales-y-para-compartir/cajun-full | 
    self.driver.get("https://ppys-dev.jnq.io/menu/personales-y-para-compartir/cajun-full")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.line-orange | 
    self.driver.find_element(By.CSS_SELECTOR, ".line-orange").click()
    # 4 | click | css=.btn-pay | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-pay").click()
    # 5 | mouseOver | css=.btn-pay | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-pay")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | css=.btn-pay | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | css=.btn:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 8 | click | css=.method-item:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".method-item:nth-child(2)").click()
    # 9 | runScript | window.scrollTo(0,111) | 
    self.driver.execute_script("window.scrollTo(0,111)")
    # 10 | click | id=terminosCondiciones | 
    self.driver.find_element(By.ID, "terminosCondiciones").click()
    # 11 | click | css=.large | 
    self.driver.find_element(By.CSS_SELECTOR, ".large").click()
    # 12 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 13 | click | css=.radio:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".radio:nth-child(2)").click()
    # 14 | click | id=payment-continue | 
    self.driver.find_element(By.ID, "payment-continue").click()
    # 15 | close |  | 
    self.driver.close()
  
