# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | /ubicacion/delivery | 
    self.driver.get("https://ppys-dev.jnq.io/ubicacion/delivery")
    # 2 | setWindowSize | 1289x924 | 
    self.driver.set_window_size(1289, 924)
    # 3 | click | css=.line-orange | 
    self.driver.find_element(By.CSS_SELECTOR, ".line-orange").click()
    # 4 | mouseOver | css=.line-orange | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".line-orange")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | css=.line-orange | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | id=mi_ubicacion | 
    self.driver.find_element(By.ID, "mi_ubicacion").click()
    # 7 | type | id=mi_ubicacion | Av inca garcilazo de la vega 1698
    self.driver.find_element(By.ID, "mi_ubicacion").send_keys("Av inca garcilazo de la vega 1698")
    # 8 | sendKeys | id=mi_ubicacion | ${KEY_ENTER}
    self.driver.find_element(By.ID, "mi_ubicacion").send_keys(Keys.ENTER)
    # 9 | click | css=.pac-item:nth-child(1) > .pac-item-query | 
    self.driver.find_element(By.CSS_SELECTOR, ".pac-item:nth-child(1) > .pac-item-query").click()
    
    # 10 | click | id=mz-ipt | 
    self.driver.find_element(By.ID, "mz-ipt").click()    
    #mz
    self.driver.find_element(By.CSS_SELECTOR, ".info-item:nth-child(1) input").send_keys("1")
    #lt
    self.driver.find_element(By.CSS_SELECTOR, ".info-item:nth-child(2) input").send_keys("2")
    
    # 17 | click | css=#otro > img | 
    self.driver.find_element(By.CSS_SELECTOR, "#otro > img").click()
    
    self.driver.find_element(By.CSS_SELECTOR, ".input-wrapper:nth-child(3) > input").send_keys("Other")
    
    # 22 | click | css=label:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(1) > input").click()
    # 23 | click | css=label:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(2) > input").click()
    
    # 24 | click | css=#modal_bottom > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, "#modal_bottom > .btn").click()
  
